import { fromEvent, map, switchMap, from, debounceTime, of } from "https://esm.sh/rxjs";

// if this is enabled, the same users will be fetched all the time
const useMockData = false;

// here starts a large object, that holds some mockdata. In order to not fetch the randomuser api all the time.

// this is mockdata which is not real. It was generated by randomuser.me
const mockData = {};

const clinicalTrialsQueryCondUrl = "https://clinicaltrials.gov/api/v2/studies?pageSize=15&query.cond=";

const randomUsersUrl = "https://randomuser.me/api/?results=20";

const illnessSearchInput = document.getElementById("illness-search");

const illnessSearchInput$ = fromEvent(illnessSearchInput, "keyup");

const foundStudies = document.getElementById("found-studies");

const patientGrid = document.getElementsByClassName("patient-grid")[0];

var selectedStudy = undefined;

var state = { studyToPatients : [] };

function addStudy(studyObj) {
	if(state.studyToPatients.length == 0) {
		document.getElementById("report-btn").classList.remove("invisible");
	}
	const study = document.createElement("li");
	study.addEventListener("click", function(event) { 
						if(selectedStudy) {
							selectedStudy.removeAttribute("class", "selected"); 
						}
						study.setAttribute("class", "selected"); 
						selectedStudy = study; 
					}
			      );
	const div = document.createElement("div");
	const studyNameElem = document.createElement("p");
        const briefTitle = studyObj.protocolSection.identificationModule.briefTitle
	state.studyToPatients.push({ name: briefTitle, patients : [] });
	
	studyNameElem.textContent = briefTitle;
	const placeNameElem = document.createElement("p");
	placeNameElem.textContent = studyObj.protocolSection.identificationModule.organization.fullName;
	div.appendChild(studyNameElem);
	div.appendChild(placeNameElem);
	study.appendChild(div);
	foundStudies.appendChild(study);
	const assignedParticipantDiv = document.createElement("div");
	const assignedParticipantTitle = document.createElement("h4");
	assignedParticipantTitle.textContent = "Assigned patients (name, phone)";
	assignedParticipantDiv.appendChild(assignedParticipantTitle);
	study.appendChild(assignedParticipantDiv);
}

illnessSearchInput$.pipe(
		map(event => event.target.value),
		debounceTime(600),
		switchMap(input => from(fetch(clinicalTrialsQueryCondUrl + input).then(response => response.json()))),
		map(data => data.studies),
	  ).subscribe(studies => { studies.forEach(study => { addStudy(study) }) });

function addPatient(name, conditions, phone, mail, imgUrl) {
	const newPatient = document.createElement("div");
	newPatient.setAttribute("class", "patient");

	const patientImg = document.createElement("img");
	patientImg.src = imgUrl;
	newPatient.appendChild(patientImg);

	const patientName = document.createElement("h4");
	patientName.textContent = name;
	newPatient.appendChild(patientName);

	const patientConditions = document.createElement("p");
	patientConditions.textContent = "Conditions: " + conditions.join(", ");
	newPatient.appendChild(patientConditions);

	const phoneElem = document.createElement("p");
	phoneElem.textContent = "Phone: " + phone;
	newPatient.appendChild(phoneElem);

	const mailElem = document.createElement("p");
	mailElem.textContent = "Mail: " + mail;
	newPatient.appendChild(mailElem);

	const assignBtnDiv = document.createElement("div");

	assignBtnDiv.textContent = "Assign to selected clinical trial";
	assignBtnDiv.addEventListener("click", (event) => {
		const assignedParticipantList = document.createElement("ul");
		const assignedParticipant = document.createElement("li");
		const nameAndPhone = name + ", " + phone
		assignedParticipant.textContent = nameAndPhone;
		assignedParticipantList.appendChild(assignedParticipant);
		selectedStudy.appendChild(assignedParticipantList);
		var studyIndex = Array.prototype.indexOf.call(foundStudies.childNodes, selectedStudy)
		state.studyToPatients[studyIndex].patients.push(nameAndPhone);

		}
	);
	newPatient.appendChild(assignBtnDiv);
	patientGrid.appendChild(newPatient);
}

function createReport() {
	console.log(state);
	// TODO create report from state
}

document.getElementById("report-btn").addEventListener("click", createReport); 

(!useMockData || !mockData ? from(fetch(randomUsersUrl).then(response => response.json())) : of(mockData))
	.pipe(map(response => response.results))
	.subscribe(results => { 
		results.forEach(result => { 
		const fullName = result.name.title + ". " + result.name.first + " " + result.name.last;
		addPatient(fullName, ["Anxiety", "Diabetes"], result.phone, result.email, result.picture.medium);
		})
	});
